## Vector-valued function with Random Fourier Features

### Imports

In [141]:
import numpy as np
from numpy.random import randn

### Values

In [142]:

dimension = 2
sigma = 2
sigma2 = 2*sigma**2

# Random Fourier features
m = 5 # number of samples
w = randn(dimension*m) / sigma # w is the same size as the dimensions times the number of samples
b = np.random.rand(m)*2*np.pi # b is the same size as number of samples

n = 100 # number of points

x1 = randn(n)/2
x2 =  randn(n)/2
x_vector = np.array([x1, x2])
# x_vector = np.block([x1,x2])

noise = randn(n) * 2e-1
y1 = np.cos(x1) + randn(n) * 1e-1
y2 = np.sin(x2) + randn(n) * 1e-1


#y1 = 1+np.sin(x1/10) + x1**2
#y2 = 0.5 * x2**2 + np.exp(x2)

y = np.block([y1, y2])

#print(y1, y2)
lam = 0.000001 # Regularisaton parameter

### Gaussian Kernel

In [143]:
def k_gauss(x, z):
    k = np.exp(-((np.linalg.norm(x-z))**2)/(sigma2))
    return k

def K_gauss(x, n, dim):
    K = np.zeros((dim*n, dim*n))
    for i in range(0, n):
        for j in range(0, n):
            k = k_gauss(x[:,i], x[:,j])
            K[i*dim][j*dim] = k
            K[i*dim+1][j*dim+1] = k
    return K

K = K_gauss(x_vector, n, dimension)
print(K)

[[1.         0.         0.92733964 ... 0.         0.96414753 0.        ]
 [0.         1.         0.         ... 0.86692721 0.         0.96414753]
 [0.92733964 0.         1.         ... 0.         0.86722471 0.        ]
 ...
 [0.         0.86692721 0.         ... 1.         0.         0.75432056]
 [0.96414753 0.         0.86722471 ... 0.         1.         0.        ]
 [0.         0.96414753 0.         ... 0.75432056 0.         1.        ]]


#### Alpha

In [144]:
# Returns a vector with length dim * n
def alpha(x, y, lam, n, dim):
    K = K_gauss(x, n, dim)
    alpha_vector = np.linalg.inv((K + lam*np.eye(dim*n))) @ y
    alpha = np.reshape(alpha_vector, (dim, n))
    return alpha

alpha_ = alpha(x_vector, y, lam, n, dimension)


### Estimated function

In [145]:
def estiamted_function(alpha, x, n):
    function = np.zeros((2, n))
    for i in range(n):
        sum1 = 0
        sum2 = 0
        for j in range(n):
            k = k_gauss(x[:, i], x[:, j])
            sum1 = sum1 + k * alpha[0, j]
            sum2 = sum2 + k * alpha[1, j]
        function[0, i] = sum1
        function[1, i] = sum2
    return function

estiamted_function(alpha_, x_vector, n)

array([[ 36135647.90234795,  35722250.07810715,  34920642.65321857,
         35933270.83273774,  36097555.31061162,  36098540.70458119,
         35982711.58516715,  35533093.57016349,  36075529.49316646,
         35855321.02973958,  32405117.15724108,  35668517.36821188,
         35735471.23326069,  36098026.10329155,  34281464.56100395,
         35615445.98896534,  36137281.06652358,  36056920.44403565,
         35547580.19728762,  35322390.656366  ,  35818900.41825636,
         35935905.8982366 ,  34273372.84597185,  35704000.14523469,
         36133126.21699078,  34779775.74559415,  35960293.29329174,
         36049698.41729197,  34033084.66491679,  36111951.2967807 ,
         34625515.98406895,  34785496.17132622,  36110416.30578892,
         33191406.30985388,  34561445.66570893,  35818714.09424737,
         35305309.64522046,  36077782.35879945,  34228842.24395387,
         34696345.01533143,  33928304.31475598,  34365930.6183788 ,
         33651198.25248374,  35786301.99408776, 