### Imports

In [184]:
import numpy as np
import sympy as sym
from numpy.random import randn
np.set_printoptions(threshold=np.inf)


### Values

In [185]:
m = 5
sigma = 2
sigma2 = 2*sigma**2
w = randn(m) / sigma
b = np.random.rand(m)*2*np.pi

n = 5
x = randn(n)/2
z = randn(n)/2 # function y

### Gaussian Kernel

In [186]:
def k_gauss(x,z):
    """R^n x R^n -> R - should be one number
    # vector is multi-dimensional

    Args:
        x (float): real value numbers
        z (float): real value numbers

    Returns:
        (vector with length n): a scalar shift-invariant Gaussian kernel
    """
    return np.exp(-((np.linalg.norm(x-z))**2)/(sigma2)) 

print(k_gauss(x,z))

0.6491327293555063


###  Scalar kernel

In [187]:
def k_approx(k, x, z):
    """scalar kernel

    Args:
        k (kernel): to test with different kernels

    Returns:
        approximated kernel: sum of feature vectors
    """
    n = len(x)
    Kxz = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            Kxz[i, j] = k(x[i], z[j])
    return Kxz

### Approximation 1

In [188]:
def psi_approx1(x):
   """
   Args:
       x (vector): vector with length n

   Returns:
       vector: vector with length n
   """
   return np.sqrt(2)*np.cos(w*x + b)

print(psi_approx1(x))

[-1.34764167 -0.36945088  1.30386626 -0.98416649 -1.36015956]


### Approximation 2

In [189]:
def phi_cos(x, w):
    return 1/np.sqrt(m) * np.cos(w.T@x)

def phi_sin(x, w):
    return 1/np.sqrt(m) * np.sin(w.T@x)

def add_phi_cos_sin(f, g, x):
    """
        [1 2 3] and [1 2 3] -> [1 1 2 2 3 3]
    """
    new_list = []
    for i in range (m):
        new_list.append(f(x))
        new_list.append(g(x))
    return new_list
"""
print("cos:", phi_cos(x))
print("sin:", phi_sin(x))
print("\n added together:", add_phi_cos_sin(phi_cos, phi_sin, x))
print("w:", w, w.T)
print("x:", x)
"""
def K_approx2(x, z, w):
    """The scalar kernel

    Args:
        x (float): random generated numbers
        z (float): random generated numbers

    Returns:
        (float): a number, which is the scalar kernel
    """
    return np.sum(phi_cos(x, w) * phi_cos(z, w)) + np.sum(phi_sin(x, w) * phi_sin(z, w))

"""
print(K_approx2(x,z))
"""

'\nprint(K_approx2(x,z))\n'

### Matrix kernels

In [190]:
# Matrix kernel
def K(k, *args): # *args: can give as many arguments as you want
    return k(*args) * np.eye(m)

# Testing for gaussian kernel
gauss_sep_ker = K(k_gauss, x, z)
print(gauss_sep_ker)

# Testing for approximation with RFF (random fourier features)
print("\n", "matrix kernel")
matrix_ker = K(K_approx2, x, z, w)
print(matrix_ker)

[[0.64913273 0.         0.         0.         0.        ]
 [0.         0.64913273 0.         0.         0.        ]
 [0.         0.         0.64913273 0.         0.        ]
 [0.         0.         0.         0.64913273 0.        ]
 [0.         0.         0.         0.         0.64913273]]

 matrix kernel
[[0.19799876 0.         0.         0.         0.        ]
 [0.         0.19799876 0.         0.         0.        ]
 [0.         0.         0.19799876 0.         0.        ]
 [0.         0.         0.         0.19799876 0.        ]
 [0.         0.         0.         0.         0.19799876]]


### Approximate function f

In [191]:
# create a list of all the w_1...w_d
d = 5
def list_d(d, n):
    list_w = []
    for i in range(d):
        w = np.random.normal(size = n) # should be N or d times
        list_w.append(w)
    return list_w

def psi(x, d, list_w):
    """
    Args:
        list_w (list): list of size d of all w, every w is of size n

    Returns:
        list: a list of cos and sin from 1 to 2d
    """
    new_list = []
    for w in list_w:
        new_list.append(phi_cos(x,w))
        new_list.append(phi_sin(x,w))
    return (1/np.sqrt(d)) * np.array(new_list)

list_w = list_d(d,n)
#print("psi list:", psi(x, d, list_w))

[array([-1.20955735,  1.34505997,  0.73845832,  0.26823018, -1.1741102 ]), array([ 0.09167165,  0.43758241,  2.07470648,  1.26568943, -0.80365787]), array([-0.84126845,  0.80366102, -0.39595866,  1.60950147, -1.2948082 ]), array([-0.33934301, -1.68601815, -0.11219988, -1.42947462, -1.44230515]), array([ 1.81953174, -0.20701292,  0.59890325,  0.80836904,  0.42113178])]
psi list: [ 0.15922183  0.12103061 -0.11163964  0.16594153  0.19633594 -0.03810771
  0.19848648 -0.02455844  0.18909027 -0.06515267]
